### ISSUE TITLE
vim使用python3会报错，有办法解决吗？

### ISSUE THREAD

**Issue by yhl41001** [BillWang139967/Vim#13]

**Comment by meetbill** [comment]
提示报错是？

**Comment by youli-jlu** [comment]
您好！我使用WSL ubantu时也会有类似的情况。

错误如下：

Error detected while processing /usr/share/vim/vimrc:
line   67:
E117: Unknown function: vundle#begin
line   73:
E492: Not an editor command:  Plugin 'gmarik/Vundle.vim'
line   74:
E492: Not an editor command:  Plugin 'Chiel92/vim-autoformat'
line   81:
E117: Unknown function: vundle#end
Press ENTER or type command to continue

在平常的ubuntu上也会有类似的报错，虽然不影响使用但是打开时会因为报错而卡顿。

**Comment by meetbill** [comment]
:(，这个报错不是使用我的项目吧

看使用的配置文件是 /usr/share/vim/vimrc
看使用的 gmarik/Vundle.vim 和 Chiel92/vim-autoformat 插件，我的项目里也是没有的

**Comment by youli-jlu** [comment]
非常感谢您的回复！

这个错误在之前并没有出现，用weget安装了您的插件后会有。不过确实和python没关系，似乎用vim打开所有的文件都会有...

不过下面这个错误是只有python文件才会出现的错误。

"test.py" 8L, 180C
Error detected while processing /home/youli-jlu/.vim/bundle/pyflakes-vim/ftplugin/python/pyflakes.vim:
line   70:
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/home/youli-jlu/.vim/bundle/pyflakes-vim/ftplugin/python/flaker.py", line 11, in <module>
    from pyflakes import checker, messages
  File "/home/youli-jlu/.vim/bundle/pyflakes-vim/ftplugin/python/pyflakes/pyflakes/checker.py", line 301
    print '  ' * self.nodeDepth + node.__class__.__name__
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('  ' * self.nodeDepth + node.__class__.__name__)?

**Comment by meetbill** [comment]
可以试下
```
mv /home/youli-jlu/.vim/bundle/pyflakes-vim /tmp
```
然后再 vim 打开下 py 文件，看是否正常

**Comment by youli-jlu** [comment]
现在没报错了，感谢您的帮助！

**Comment by meetbill** [comment]
好的
