### ISSUE TITLE
出现点小问题

### ISSUE THREAD

**Issue by mwtao** [BillWang139967/Vim#3]
用您的脚本配置好vim后，发现在插入模式中，每当输入{，“，‘，等符号时都会报错：
{
**处理 function <SNR>21_RestoreSettings 时发生错误:
第    4 行:
E121: 未定义的变量: s:ShowMode
请按 ENTER 或其它命令继续
处理 function <SNR>21_RestoreSettings 时发生错误:
第    4 行:
E15: 无效的表达式: s:ShowMode
请按 ENTER 或其它命令继续
处理 function <SNR>21_RestoreSettings 时发生错误:
第    7 行:
E121: 未定义的变量: s:CmdHeight
请按 ENTER 或其它命令继续
处理 function <SNR>21_RestoreSettings 时发生错误:
第    7 行:
E15: 无效的表达式: "set cmdheight=".s:CmdHeight**
}
请问需要怎么配置呢？

**Comment by meetbill** [comment]
操作系统是？

**Comment by mwtao** [comment]
ubuntu16.04

**Comment by meetbill** [comment]
我在我本地安装了1604安装了下Vim,使用上没有出现上面问题，您是不是自己加过一些插件导致了冲突

可以
```
#cd `~
#rm -rf .vim*
```
然后再操作一遍

**Comment by Luiniux** [comment]
非常感谢，应该是我和我之前在
