### ISSUE TITLE
32位系统可以用吗，我这边报错（之前在64位用的很好哈）

### ISSUE THREAD

**Issue by vieyahn** [BillWang139967/Vim#9]
Error detected while processing /home/nw/.vimrc:
line   13:
E319: Sorry, the command is not available in this version: filetype plugin indent on
line   16:
E319: Sorry, the command is not available in this version: syntax on
line   35:
E518: Unknown option: foldenable
line   36:
E518: Unknown option: foldmethod=marker
line   50:
E538: No mouse support: mouse=c
line   76:
E319: Sorry, the command is not available in this version: autocmd BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") |     exe "normal g'\"" | endif
line   80:
E319: Sorry, the command is not available in this version: let mapleader=","
line   94:
E319: Sorry, the command is not available in this version: let OpenDir=system("pwd")
line   99:
E319: Sorry, the command is not available in this version: let g:NERDTreeWinPos="right"
line  100:
E319: Sorry, the command is not available in this version: let g:NERDTreeWinSize=25
line  101:
E319: Sorry, the command is not available in this version: let g:NERDTreeShowLineNumbers=1
line  114:
E319: Sorry, the command is not available in this version: let g:OmniCpp_DefaultNamespaces=["std"]
line  115:
E319: Sorry, the command is not available in this version: let g:OmniCpp_MayCompleteScope=1
line  116:
E319: Sorry, the command is not available in this version: let g:OmniCpp_SelectFirstItem=2
line  124:
E319: Sorry, the command is not available in this version: let g:LookupFile_TagExpr='"./tags.filename"'
line  125:
E319: Sorry, the command is not available in this version: let g:LookupFile_MinPatLength=2
line  126:
E319: Sorry, the command is not available in this version: let g:LookupFile_PreserveLastPattern=0
line  127:
E319: Sorry, the command is not available in this version: let g:LookupFile_PreservePatternHistory=1
line  128:
E319: Sorry, the command is not available in this version: let g:LookupFile_AlwaysAcceptFirst=1
line  129:
E319: Sorry, the command is not available in this version: let g:LookupFile_AllowNewFiles=0
line  131:
E484: Can't open file /usr/share/vim/vim74/ftplugin/man.vim
line  133:
E319: Sorry, the command is not available in this version: let g:snips_author="Du Jianfeng"
line  134:
E319: Sorry, the command is not available in this version: let g:snips_email="cmdxiaoha@163.com"
line  135:
E319: Sorry, the command is not available in this version: let g:snips_copyright="SicMicro, Inc"
line  137:
E319: Sorry, the command is not available in this version: function! RunShell(Msg, Shell)
line  138:
E319: Sorry, the command is not available in this version: ^Iecho a:Msg . '...'
line  139:
E319: Sorry, the command is not available in this version: ^Icall system(a:Shell)
line  140:
E319: Sorry, the command is not available in this version: ^Iechon 'done'
line  141:
E319: Sorry, the command is not available in this version: endfunction
line  166:
E319: Sorry, the command is not available in this version: autocmd BufRead,BufNewFile *.{md,mdown,mkd,mkdn,markdown,mdwn} set filetype=markdown
line  167:
E319: Sorry, the command is not available in this version: autocmd BufNewFile *.py,*.cpp,*.[ch],*.sh,*.java,*.{md,mdown,mkd,mkdn,markdown,mdwn} exec ":call SetTitle()" 
line  168:
E319: Sorry, the command is not available in this version: autocmd FileType python set omnifunc=pythoncomplete#Complete
line  170:
E319: Sorry, the command is not available in this version: func SetTitle() 
line  230:
E319: Sorry, the command is not available in this version: ^Iautocmd BufNewFile * normal G
line  231:
E319: Sorry, the command is not available in this version: endfunc 
line  249:
E319: Sorry, the command is not available in this version: func! CompileRunGcc()
line  250:
E319: Sorry, the command is not available in this version: ^Iexec "w"
line  263:
E319: Sorry, the command is not available in this version: endfunc
line  266:
E319: Sorry, the command is not available in this version: func! Rungdb()
line  267:
E319: Sorry, the command is not available in this version: ^Iexec "w"
line  268:
E319: Sorry, the command is not available in this version: ^Iexec "!gcc % -g -o %<"
line  269:
E319: Sorry, the command is not available in this version: ^Iexec "!gdb ./%<"
line  270:
E319: Sorry, the command is not available in this version: endfunc
line  275:
E319: Sorry, the command is not available in this version: let g:winManagerWindowLayout='FileExplorer|TagList'
line  280:
E319: Sorry, the command is not available in this version: let Tlist_Sort_Type = "name"    
line  281:
E319: Sorry, the command is not available in this version: let Tlist_Compart_Format = 1    
line  282:
E319: Sorry, the command is not available in this version: let Tlist_Exist_OnlyWindow = 1  
line  283:
E319: Sorry, the command is not available in this version: let Tlist_File_Fold_Auto_Close = 0  
line  285:
E319: Sorry, the command is not available in this version: let Tlist_Show_One_File=1         
line  287:
E518: Unknown option: autochdir
line  288:
E319: Sorry, the command is not available in this version: let Tlist_Ctags_Cmd = '/usr/bin/ctags' 
line  289:
E319: Sorry, the command is not available in this version: let Tlist_Show_One_File = 1
line  290:
E319: Sorry, the command is not available in this version: let Tlist_Exit_OnlyWindow = 1 
line  291:
E319: Sorry, the command is not available in this version: let g:Tlist_Auto_Update=1
line  293:
E319: Sorry, the command is not available in this version: let Tlist_WinWidth=25
line  294:
E319: Sorry, the command is not available in this version: let g:Tlist_Enable_Fold_Column=0
line  305:
E319: Sorry, the command is not available in this version: let g:DoxygenToolkit_briefTag_funcName="yes"
line  310:
E319: Sorry, the command is not available in this version: let g:pydiction_location = '~/.vim/tools/pydiction/complete-dict'
line  316:
E319: Sorry, the command is not available in this version: autocmd vimenter * if !argc() | NERDTree | endif
line  318:
E319: Sorry, the command is not available in this version: autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
Press ENTER or type command to continue

**Comment by meetbill** [comment]
@vieyahn 不支持 :(
